source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXCityPicker_Example' do
  pod "BXCityPicker", :path => "../"
  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end

target 'BXCityPicker_Tests' do
  pod "BXCityPicker", :path => "../"

  
end
