platform :ios, '8.1'
use_frameworks!

target 'BXCityPicker_Example' do
  pod "BXCityPicker", :path => "../"
  pod "BXForm", :path => "../../BXForm"
#  pod 'Reveal-iOS-SDK', :configurations => ['Debug']
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
