source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BXCityPicker_Example', :exclusive => true do
  pod "BXCityPicker", :path => "../"
end

target 'BXCityPicker_Tests', :exclusive => true do
  pod "BXCityPicker", :path => "../"

  
end
